### ISSUE TITLE
README SO-ES06 RIFERIMENTI README

### ISSUE THREAD

**Issue by mRuggi** [SO-unina/esercitazioni#1]
Il readme descrittivo di [questa](https://github.com/SO-unina/esercitazioni/tree/main/SO-ES06-Semafori/2_semaphores_1ex) esercitazione ha riferimenti a file non presenti
procedure.h è diventato semafori.h 
procedure.c è diventato semafori.c
semafori.c a cui ci si riferisce per l'implementazione del main è diventato main.c
nel commit: 8eb9efcee32b15787fa1eec43fef6b064d89cbb1
ma i riferimenti nel readme non sono stati aggiornati

**Comment by ldesi** [comment]
Caro Matteo,

Grazie per avermi fatto notare il bug.

Luigi De Simone
